language: python
before_install:
- pip install pycodestyle
install:
- pip install -r requirements.txt
- python setup.py install
script:
- find . -name \*.py -exec pycodestyle --max-line-length=120 --ignore=E402 {} +
- pytest --cov=artellapipe
- sphinx-apidoc -f -e -o docs/sphinx artellapipe
- sphinx-build -M html ./docs/sphinx ./
after_success:
- coveralls
- cd html && touch .nojekyll && cd ../
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: "$GITHUB_TOKEN"
    keep_history: true
    local_dir: html
    on:
      branch: master
  - provider: pypi
    skip_cleanup: true
    user: tpoveda
    password:
      secure: Rhtf1dCLJu0prv+Y+AAMp//h/BFo4nV0HLzbAXD0Q6QBIc4rPZtIdDI8hm3SmD8+c0z8lvrAOpNzMTM/rcqJA3rznKZWRdasDImXIlMdB3hwGuPkvKsVfSL0je4Gp7HKRQtaAtdnIYGh6bfM6gO7wp9f1soVlV4fyaZJNnEOCXrmxYLHTaqakx2R4+rwWvSFbaJv+ZzteY9djUs8CddOsQoB8KJ+D+06+GFpiV8SjvfHuPiFpypzCQ/VVAOlkEhyYUSkeebOAXvkTyH3Hw/29nF8Pqb1/45URHTq5bzwYi4GUMPoJ471D6it9avyGus6wmqLdipz3ijHT+rXIMEm9JPqTYiAG64T7FQVCiRSRKUjXJ4ycGDbWfdcn5Bk3DKFVLVWRl7U9qJnUNvgiSomylllBMNCN1rMIJPT+XmSdno88Aa/+2kz+VKzfsfgqR7q68KpN42c1yzAyePHDX9kySwxdaTUVu3kez5YwQN5anhmEpud/c7BrPnQAYSvZ9cXaIQUuYYRGXBqKUqjGz0spyqHeyOcrTZrxII+h4faNujcNJtFT2XaSPx9zncd/7N5caistBT9W8x8ohgIVxKnQwrY7LoF23EIzoya1Zq9XNHdi6HgAc4VyR79SAfVe3FnNEA9wXiCo2n0CrvwI/3kLBjUVxlDP9A5xfRhWs/a42g=
    on:
      branch: master
      tags: true